collections:
  - name: "members"
    label: "Members"
    folder: "data/members"
    create: true
    slug: "{{name}}"
    format: "json"
    fields:
      - { name: "name", label: "Full Name", widget: "string" }
