site:
  name: "SLB SMKMIL Official Website"
  logo: "/logo slb rbg.png"
  description: "Student Leader Board - SMK Munshi Ibrahim Labis"

content:
  collections:
    - id: "members"
      name: "Members"
      type: "folder"
      path: "data/members"
      format: "json"
      slug_field: "name"
      create: true
      fields:
        - id: "name"
          name: "Full Name"
          type: "string"
        - id: "position"
          name: "Position / Title"
          type: "string"
        - id: "class"
          name: "Class"
          type: "string"
        - id: "photo"
          name: "Photo (.jpg only)"
          type: "image"
          directory: "image"
          public_path: "/image"
        - id: "section"
          name: "Section"
          type: "select"
          options:
            - { label: "Committee of Student Leader Board", value: "committee" }
            - { label: "Member of Student Leaders Board", value: "student" }
            - { label: "Internship Member of Student Leaders Board", value: "internship" }
