media:
  input: image
  output: /image

content:
  - name: home
    label: Home Page
    type: file
    file: index.html
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Page Content
        type: rich-text

  - name: about
    label: About Page
    type: file
    file: about.html
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Page Content
        type: rich-text

  - name: contact
    label: Contact Page
    type: file
    file: contact.html
    fields:
      - name: title
        label: Page Title
        type: string
      - name: body
        label: Page Content
        type: rich-text
