# .pages.yml
media: image

content:
  - name: members
    label: Members
    type: collection
    path: data/members # This is where the JSON files will be saved
    format: json
    view:
      fields: [name, order, position, class, section]
      primary: name
      sort: [order, name]
    filename: "{slug}" # CMS adds .json automatically
    fields:
      - { name: name, label: "Full Name", type: string, required: true }
      - { name: slug, label: "URL Slug", type: string, required: true }
      - { name: order, label: "Order", type: number, default: 100 }
      - { name: position, label: "Position", type: string }
      - { name: class, label: "Class", type: string }
      - { name: photo, label: "Photo", type: image }
      - { 
          name: section, 
          label: "Section", 
          type: select, 
          options: ["committee", "student", "internship"],
          required: true 
        }