media: image

content:
  - name: members
    label: Members
    type: collection
    path: data/members
    format: json
    view:
      fields: [name, order, position, section]
      primary: name
      sort: [order, name]
    filename: "{slug}"
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
      - name: slug
        label: URL Slug (for filename)
        type: string
        required: true
        description: "e.g., dayang-nurhasnaa"
      - name: order
        label: Display Order
        type: number
        default: 100
      - name: position
        label: Position / Title
        type: string
      - name: class
        label: Class
        type: string
      - name: photo
        label: Photo
        type: image
      - name: section
        label: Section
        type: select
        required: true
        options:
          values:
            - committee
            - student
            - internship

  - name: about
    label: About Us
    type: file
    path: about-us.html
    format: raw
    fields:
      - name: body
        label: Page Content
        type: rich-text