# .pages.yml
media: image

content:
  - name: members
    label: Members
    type: collection
    path: data/members
    format: json
    view:
      fields: [name, position, class, section]
      primary: name
      sort: [name, position]
      default:
        sort: name
        order: asc
    filename: "{name}.json"
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
      - name: position
        label: Position / Title
        type: string
        required: true
      - name: class
        label: Class
        type: string
        required: true
      - name: photo
        label: Photo
        type: image
        required: true
      - name: section
        label: Section
        type: string
        required: true
        description: "Enter: committee, student, or internship (lowercase)"

  - name: about
    label: About Us
    type: file
    path: about-us.html
    format: raw
    fields:
      - name: body
        label: Page Content
        type: rich-text