# .pages.yml
backend:
  name: git-gateway
  branch: main

media_folder: "/image"
public_folder: "/image"

collections:
  - name: "members"
    label: "Members"
    folder: "data/members"
    create: true
    fields:
      - {label: "Full Name", name: "name", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Class", name: "class", widget: "string"}
      - {label: "Photo", name: "photo", widget: "image"}
      - label: "Section"
        name: "section"
        widget: "select"
        options: ["committee", "student", "internship"]