# .pages.yml
media: image

content:
  - name: members
    label: Members
    type: collection
    path: data/members
    format: json
    view:
      fields: [name, slug, position, class, section]
      primary: name
      sort: [name, position]
      default:
        sort: name
        order: asc
    filename: "{slug}.json"  # 使用 slug 字段
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
      - name: slug
        label: URL Slug (用于文件名)
        type: string
        required: true
        description: "请输入英文小写字母和连字符，例如：dayang-nurhasnaa"
        pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
      - name: position
        label: Position / Title
        type: string
      - name: class
        label: Class
        type: string
      - name: photo
        label: Photo
        type: image
      - name: section
        label: Section
        type: string
        required: true
        description: "Enter: committee, student, or internship (lowercase)"

  - name: about
    label: About Us
    type: file
    path: about-us.html
    format: raw
    fields:
      - name: body
        label: Page Content
        type: rich-text

  - name: manifest
    label: Member Manifest
    type: file
    path: data/members/manifest.json
    format: json
    fields:
      - name: body
        label: Member File List
        type: code
        options:
          language: json