media:
  input: image/uploads
  output: /image/uploads

content:
  - name: home
    label: Home
    type: file
    file: index.html
    fields:
      - name: title
        label: 标题
        type: string
      - name: body
        label: 主要内容
        type: rich-text

  - name: about
    label: About Us
    type: file
    file: about-us.html
    fields:
      - name: title
        label: 标题
        type: string
      - name: body
        label: 主要内容
        type: rich-text

  - name: info
    label: Information
    type: file
    file: info.html
    fields:
      - name: title
        label: 标题
        type: string
      - name: body
        label: 主要内容
        type: rich-text

  - name: activity
    label: Activity
    type: file
    file: activity.html
    fields:
      - name: title
        label: 标题
        type: string
      - name: body
        label: 主要内容
        type: rich-text

  - name: register
    label: Registration
    type: file
    file: register.html
    fields:
      - name: title
        label: 标题
        type: string
      - name: body
        label: 主要内容
        type: rich-text

  - name: subscribe
    label: Subscribe
    type: file
    file: subscribe.html
    fields:
      - name: title
        label: 标题
        type: string
      - name: body
        label: 主要内容
        type: rich-text

  - name: contact
    label: Contact Us
    type: file
    file: contact.html
    fields:
      - name: title
        label: 标题
        type: string
      - name: body
        label: 主要内容
        type: rich-text
