# .pages.yml
media: image

content:
  - name: members
    label: Members
    type: collection
    path: data/members
    format: json
    view:
      fields: [name, position, class, section]
      primary: name
      sort: [name, position]
      default:
        sort: name
        order: asc
    filename: "{name}.json"
    fields:
      - name: name
        label: Full Name
        type: string
        required: true
      - name: position
        label: Position / Title
        type: string
      - name: class
        label: Class
        type: string
      - name: photo
        label: Photo
        type: image
      - name: section
        label: Section
        type: select
        options:
          - label: Committee of Student Leader Board
            value: committee
          - label: Member of Student Leaders Board
            value: student
          - label: Internship Member of Student Leaders Board
            value: internship

  - name: about
    label: About Us
    type: file
    path: about-us.md
    format: yaml-frontmatter
    fields:
      - name: title
        label: Title
        type: string
        default: "About Us"
      - name: description
        label: Description
        type: text
      - name: body
        label: Page Content
        type: rich-text