media:
  input: image
  output: /image

content:
  - name: homepage
    label: Homepage
    type: file
    file: index.html
    fields:
      - name: title
        label: Title
        type: string
      - name: content
        label: Content
        type: rich-text
