collections:
  # === Member Collection ===
  - type: collection
    name: members
    label: Members
    path: data/members/{{slug}}.json
    create: true
    fields:
      - name: name
        label: Full Name
        component: text
      - name: position
        label: Position / Title
        component: text
      - name: class
        label: Class
        component: text
      - name: photo
        label: Photo
        component: image
      - name: section
        label: Section
        component: select
        options:
          - label: Committee of Student Leader Board
            value: committee
          - label: Member of Student Leaders Board
            value: student
          - label: Internship Member of Student Leaders Board
            value: internship

  # === Static Page ===
  - type: file
    name: aboutus
    label: About Us Page
    path: about-us.html
    fields:
      - name: body
        label: Page Content
        component: markdown
