# .pages.yml
pages:
  - name: members
    label: Members
    path: content/members
    format: json
    fields:
      - name: name
        label: Full Name
        type: text
      - name: position
        label: Position / Title
        type: text
      - name: class
        label: Class
        type: text
      - name: photo
        label: Photo
        type: image
      - name: section
        label: Section
        type: select
        options:
          - label: Committee of Student Leader Board
            value: committee
          - label: Member of Student Leaders Board
            value: student
          - label: Internship Member of Student Leaders Board
            value: internship

  - name: about
    label: About Us
    path: content/pages
    file: about-us.html
    format: html
    fields:
      - name: title
        label: Title
        type: text
      - name: content
        label: Content
        type: markdown