# .pages.yml 的正确格式

collections:
  - name: members
    label: Members
    path: content/members
    extension: json
    format: json
    fields:
      - name: name
        label: Full Name
        component: text
        required: true
      - name: position
        label: Position / Title
        component: text
      - name: class
        label: Class
        component: text
      - name: photo
        label: Photo
        component: image
        required: false
      - name: section
        label: Section
        component: select
        options:
          - label: Committee of Student Leader Board
            value: committee
          - label: Member of Student Leaders Board
            value: student
          - label: Internship Member of Student Leaders Board
            value: internship

  - name: pages
    label: Pages
    path: content/pages
    extension: md
    format: frontmatter
    fields:
      - name: title
        label: Title
        component: text
        required: true
      - name: body
        label: Content
        component: markdown