collections:
  - name: members
    label: Members
    path: data/members
    extension: json
    create: true
    fields:
      - name: name
        label: Full Name
        component: text
      - name: position
        label: Position / Title
        component: text
      - name: class
        label: Class
        component: text
      - name: photo
        label: Photo
        component: image
      - name: section
        label: Section
        component: select
        options:
          - label: Committee of Student Leader Board
            value: committee
          - label: Member of Student Leaders Board
            value: student
          - label: Internship Member of Student Leaders Board
            value: internship

  - name: aboutus
    label: About Us
    path: content/pages
    file: about-us.md
    fields:
      - name: title
        label: Title
        component: text
        default: "About Us"
      - name: body
        label: Page Content
        component: markdown