backend:
  name: github
  repo: slbsmkmil/official-webside
  branch: main

media_folder: "image/uploads"
public_folder: "/image/uploads"

collections:
  - name: "pages"
    label: "网站页面"
    files:
      - label: "首页"
        name: "index"
        file: "index.html"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "内容", name: "body", widget: "markdown" }

      - label: "关于我们"
        name: "about-us"
        file: "about-us.html"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "内容", name: "body", widget: "markdown" }

      - label: "Information"
        name: "info"
        file: "info.html"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "内容", name: "body", widget: "markdown" }

      - label: "Activity"
        name: "activity"
        file: "activity.html"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "内容", name: "body", widget: "markdown" }

      - label: "Registration"
        name: "register"
        file: "register.html"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "内容", name: "body", widget: "markdown" }

      - label: "Subscribe"
        name: "subscribe"
        file: "subscribe.html"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "内容", name: "body", widget: "markdown" }

      - label: "Contact Us"
        name: "contact"
        file: "contact.html"
        fields:
          - { label: "标题", name: "title", widget: "string" }
          - { label: "内容", name: "body", widget: "markdown" }
