backend:
  name: github
  repo: slbsmkmil/official-webside
  branch: main
  base_url: https://api.netlify.com

media_folder: "images"        # 图片上传存放位置
public_folder: "/images"

collections:
  - name: "pages"
    label: "网站页面"
    files:
      - file: "index.html"
        label: "Home 页面"
        fields:
          - { name: "title", label: "标题", widget: "string" }
          - { name: "body", label: "内容", widget: "markdown" }

      - file: "about-us.html"
        label: "About Us 页面"
        fields:
          - { name: "title", label: "标题", widget: "string" }
          - { name: "body", label: "内容", widget: "markdown" }

      - file: "info.html"
        label: "Information 页面"
        fields:
          - { name: "title", label: "标题", widget: "string" }
          - { name: "body", label: "内容", widget: "markdown" }

      - file: "activity.html"
        label: "Activity 页面"
        fields:
          - { name: "title", label: "标题", widget: "string" }
          - { name: "body", label: "内容", widget: "markdown" }

      - file: "register.html"
        label: "Registration 页面"
        fields:
          - { name: "title", label: "标题", widget: "string" }
          - { name: "body", label: "内容", widget: "markdown" }

      - file: "subscribe.html"
        label: "Subscribe 页面"
        fields:
          - { name: "title", label: "标题", widget: "string" }
          - { name: "body", label: "内容", widget: "markdown" }

      - file: "contact.html"
        label: "Contact 页面"
        fields:
          - { name: "title", label: "标题", widget: "string" }
          - { name: "body", label: "内容", widget: "markdown" }
